### ISSUE TITLE
No keystrokes recorded

### ISSUE THREAD

**Issue by maximilienGilet** [skarrmann/morizon#3] opened 2024-01-08 10:29 UTC
Hi

I've built a Morizon following the BOM and flashing guide. I successfully flashed the pro micro (showing `HID console connected: Steven Karrmann Morizon (FEED:0000:0001)` in QMK Toolbox).

However I don't get any keys recorded. I tried re-flashing multiple times and double checked the diodes but nothing seems to work.

What could be the issue ?

**Comment by skarrmann** [comment] 2024-01-08 14:07
Hello!

I will confirm the Morizon firmware flash works with QMK Toolbox within a couple days, hopefully tonight. QMK Toolbox worked when I last tried it about a year ago, and QMK CLI works.

Which model Pro Micro are you using? Did you use sockets to connect it the PCB? If so, I recommend removing the Pro Micro and testing it separately. Use a wire to connect pins 14 (B3) and 7 (E6) - this should send keystroke for letter "L". If the Pro Micro works while removed from the PCB, then it is a PCB or soldering issue. If the Pro Micro does not work while removed from the PCB, then it is an issue with the microcontroller or the firmware.

Please let me know how your testing goes, and I will try flashing using the QMK Toolbox soon and let you know how that works.

**Comment by skarrmann** [comment] 2024-01-08 22:41
I testing flashing the Morizon firmware with QMK Toolbox. It worked for me, and keystrokes work afterwards. Here is what I did:

1. Download and install [qmk_toolbox_install.exe](https://github.com/qmk/qmk_toolbox/releases/download/0.2.2/qmk_toolbox_install.exe).
2. When running QMK Toolbox for the first time, a prompt appeared: "Would you like to install drivers for your devices?". Click "Yes", and waited for the drivers to install.
3. Compile and download the [default Morizon layout firmware from QMK Configurator](https://config.qmk.fm/#/morizon/LAYOUT).
4. In QMK Toolbox, open the firmware file.
5. Connect the Morizon keyboard to the PC. (My Pro Micro is has a blue PCB and USB Micro port)
6. Press the reset button on the Morizon PCB, and then in QMK Toolbox click the "Flash" button.

After flashing finished, the keyboard worked with the default layout loaded. In case it helps, here is my output from flashing in QMK Toolbox:
```
Caterina device connected (usbser): Microsoft USB Serial Device (COM3) (2341:0037:0001) [COM3]
Attempting to flash, please don't remove device
> avrdude.exe -p atmega32u4 -c avr109 -U flash:w:"C:\Users\skarrmann\Downloads\morizon_layout_mine.hex":i -P COM3
> 
> Connecting to programmer: .
> Found programmer: Id = "CATERIN"; type = S
>     Software Version = 1.0; No Hardware Version given.
> Programmer supports auto addr increment.
> Programmer supports buffered memory access with buffersize=128 bytes.
> 
> Programmer supports the following devices:
>     Device code: 0x44
> 
> avrdude.exe: AVR device initialized and ready to accept instructions
> 
> Reading | ################################################## | 100% 0.00s
> 
> avrdude.exe: Device signature = 0x1e9587 (probably m32u4)
> avrdude.exe: NOTE: "flash" memory has been specified, an erase cycle will be performed
>              To disable this feature, specify the -D option.
> avrdude.exe: erasing chip
> avrdude.exe: reading input file "C:\Users\skarrmann\Downloads\morizon_layout_mine.hex"
> avrdude.exe: writing flash (18020 bytes):
> 
> Writing | ################################################## | 100% 1.33s
> 
> avrdude.exe: 18020 bytes of flash written
> avrdude.exe: verifying flash memory against C:\Users\skarrmann\Downloads\morizon_layout_mine.hex:
> avrdude.exe: load data flash data from input file C:\Users\skarrmann\Downloads\morizon_layout_mine.hex:
> avrdude.exe: input file C:\Users\skarrmann\Downloads\morizon_layout_mine.hex contains 18020 bytes
> avrdude.exe: reading on-chip flash data:
> 
> Reading | ################################################## | 100% 0.13s
> 
> avrdude.exe: verifying ...
> avrdude.exe: 18020 bytes of flash verified
> 
> avrdude.exe: safemode: Fuses OK (E:FB, H:D8, L:FF)
> 
> avrdude.exe done.  Thank you.
> 
Flash complete
HID console connected: Steven Karrmann Morizon (FEED:0000:0001)
```

So it seems the default Morizon firmware is okay, and it can be installed with QMK Toolbox.

Let me know how your testing goes.

**Comment by skarrmann** [comment] 2024-01-22 22:26
@maximilienGilet Have you had a chance to further troubleshoot this issue?

**Comment by skarrmann** [comment] 2024-02-13 20:27
I am closing this issue since I cannot reproduce it, and have received no reply. The Morizon PCB and flashing the firmware with QMK Toolbox on a Pro Micro worked in my testing above.

@maximilienGilet If you are still having an issue, experienced QMK users may be able to help troubleshoot. My advice above might help diagnose the issue. Good luck!

**Closed as not planned** 2024-02-13 20:27 UTC

**Comment by maximilienGilet** [comment] 2024-02-23 23:14
Hi @skarrmann, sorry for the delay I have been quite busy since then and didn't received Github notifications.

I have this exact pro micro (with USB C) : https://fr.aliexpress.com/item/32846843498.html

**Comment by maximilienGilet** [comment] 2024-02-26 10:25
Hi @skarrmann, I just tested the pro micro and the pin 7 + 14 shortcut works, it triggers an L.
I will check my soldering again

**Comment by skarrmann** [comment] 2024-02-26 13:35
@maximilienGilet That is good! Then there is likely is a soldering issue. A multimeter would be helpful for checking electrical continuity between pins and confirming there are no solder bridges. Good luck!

**Comment by maximilienGilet** [comment] 2024-02-26 21:01
Hi again @skarrmann !
After a lot of tinkering i figured out that inverting the diodes position makes it working somehow, but the matrix is inverted.

As i'm typing this I think it might not be the diodes but the pro micro needing to be flipped (I soldered it with the components on the upper side). Could it be that ?

EDIT: I looked at my other PCB and yep... I have to flip the diodes again and the pro micro because I missed the fact it needs to be mounted upside down

![IMG_0265](https://github.com/skarrmann/morizon/assets/10434870/56ef533c-52b5-4b00-bd41-212a33470140)

**Comment by skarrmann** [comment] 2024-02-26 22:44
Yes, that is the issue! The Pro Micro needs to be soldered with the components facing down, so its pin labels match the labels printed on the PCB.

I am glad you discovered the problem, and I hope you can fix it without too much trouble.

**Comment by maximilienGilet** [comment] 2024-02-27 13:52
Thank you for your help !
